[project]
version = "0.1.0"
name = "monorake"

cincludes = [
    "3rp/libsass-3.6.4/include/"
]
cobjects = [
    "3rp/lua-5.3.5/src/lapi.c",
    "3rp/lua-5.3.5/src/lauxlib.c",
    "3rp/lua-5.3.5/src/lbaselib.c",
    "3rp/lua-5.3.5/src/lbitlib.c",
    "3rp/lua-5.3.5/src/lcode.c",
    "3rp/lua-5.3.5/src/lcorolib.c",
    "3rp/lua-5.3.5/src/lctype.c",
    "3rp/lua-5.3.5/src/ldblib.c",
    "3rp/lua-5.3.5/src/ldebug.c",
    "3rp/lua-5.3.5/src/ldo.c",
    "3rp/lua-5.3.5/src/ldump.c",
    "3rp/lua-5.3.5/src/lfunc.c",
    "3rp/lua-5.3.5/src/lgc.c",
    "3rp/lua-5.3.5/src/linit.c",
    "3rp/lua-5.3.5/src/liolib.c",
    "3rp/lua-5.3.5/src/llex.c",
    "3rp/lua-5.3.5/src/lmathlib.c",
    "3rp/lua-5.3.5/src/lmem.c",
    "3rp/lua-5.3.5/src/loadlib.c",
    "3rp/lua-5.3.5/src/lobject.c",
    "3rp/lua-5.3.5/src/lopcodes.c",
    "3rp/lua-5.3.5/src/loslib.c",
    "3rp/lua-5.3.5/src/lparser.c",
    "3rp/lua-5.3.5/src/lstate.c",
    "3rp/lua-5.3.5/src/lstring.c",
    "3rp/lua-5.3.5/src/lstrlib.c",
    "3rp/lua-5.3.5/src/ltable.c",
    "3rp/lua-5.3.5/src/ltablib.c",
    "3rp/lua-5.3.5/src/ltm.c",
    "3rp/lua-5.3.5/src/lundump.c",
    "3rp/lua-5.3.5/src/lutf8lib.c",
    "3rp/lua-5.3.5/src/lvm.c",
    "3rp/lua-5.3.5/src/lzio.c",

    "3rp/libsass-3.6.4/src/c99func.c",
    "3rp/libsass-3.6.4/src/cencode.c",
    "3rp/libsass-3.6.4/src/sass_values.cpp",
    "3rp/libsass-3.6.4/src/output.cpp",
    "3rp/libsass-3.6.4/src/fn_utils.cpp",
    "3rp/libsass-3.6.4/src/sass.cpp",
    "3rp/libsass-3.6.4/src/listize.cpp",
    "3rp/libsass-3.6.4/src/ast_sel_weave.cpp",
    "3rp/libsass-3.6.4/src/util.cpp",
    "3rp/libsass-3.6.4/src/ast_sel_super.cpp",
    "3rp/libsass-3.6.4/src/parser_selectors.cpp",
    "3rp/libsass-3.6.4/src/ast_supports.cpp",
    "3rp/libsass-3.6.4/src/check_nesting.cpp",
    "3rp/libsass-3.6.4/src/values.cpp",
    "3rp/libsass-3.6.4/src/plugins.cpp",
    "3rp/libsass-3.6.4/src/fn_numbers.cpp",
    "3rp/libsass-3.6.4/src/fn_selectors.cpp",
    "3rp/libsass-3.6.4/src/ast_fwd_decl.cpp",
    "3rp/libsass-3.6.4/src/util_string.cpp",
    "3rp/libsass-3.6.4/src/eval_selectors.cpp",
    "3rp/libsass-3.6.4/src/cssize.cpp",
    "3rp/libsass-3.6.4/src/c2ast.cpp",
    "3rp/libsass-3.6.4/src/parser.cpp",
    "3rp/libsass-3.6.4/src/operators.cpp",
    "3rp/libsass-3.6.4/src/fn_maps.cpp",
    "3rp/libsass-3.6.4/src/emitter.cpp",
    "3rp/libsass-3.6.4/src/ast_sel_cmp.cpp",
    "3rp/libsass-3.6.4/src/source.cpp",
    "3rp/libsass-3.6.4/src/error_handling.cpp",
    "3rp/libsass-3.6.4/src/ast.cpp",
    "3rp/libsass-3.6.4/src/ast2c.cpp",
    "3rp/libsass-3.6.4/src/inspect.cpp",
    "3rp/libsass-3.6.4/src/sass2scss.cpp",
    "3rp/libsass-3.6.4/src/ast_values.cpp",
    "3rp/libsass-3.6.4/src/file.cpp",
    "3rp/libsass-3.6.4/src/base64vlq.cpp",
    "3rp/libsass-3.6.4/src/context.cpp",
    "3rp/libsass-3.6.4/src/json.cpp",
    "3rp/libsass-3.6.4/src/fn_lists.cpp",
    "3rp/libsass-3.6.4/src/sass_functions.cpp",
    "3rp/libsass-3.6.4/src/ast_sel_unify.cpp",
    "3rp/libsass-3.6.4/src/units.cpp",
    "3rp/libsass-3.6.4/src/eval.cpp",
    "3rp/libsass-3.6.4/src/backtrace.cpp",
    "3rp/libsass-3.6.4/src/bind.cpp",
    "3rp/libsass-3.6.4/src/lexer.cpp",
    "3rp/libsass-3.6.4/src/environment.cpp",
    "3rp/libsass-3.6.4/src/memory/shared_ptr.cpp",
    "3rp/libsass-3.6.4/src/memory/allocator.cpp",
    "3rp/libsass-3.6.4/src/sass_context.cpp",
    "3rp/libsass-3.6.4/src/remove_placeholders.cpp",
    "3rp/libsass-3.6.4/src/fn_miscs.cpp",
    "3rp/libsass-3.6.4/src/fn_strings.cpp",
    "3rp/libsass-3.6.4/src/constants.cpp",
    "3rp/libsass-3.6.4/src/fn_colors.cpp",
    "3rp/libsass-3.6.4/src/prelexer.cpp",
    "3rp/libsass-3.6.4/src/expand.cpp",
    "3rp/libsass-3.6.4/src/stylesheet.cpp",
    "3rp/libsass-3.6.4/src/position.cpp",
    "3rp/libsass-3.6.4/src/source_map.cpp",
    "3rp/libsass-3.6.4/src/color_maps.cpp",
    "3rp/libsass-3.6.4/src/extender.cpp",
    "3rp/libsass-3.6.4/src/utf8_string.cpp",
    "3rp/libsass-3.6.4/src/ast_selectors.cpp",
    "3rp/libsass-3.6.4/src/to_value.cpp",
    "3rp/libsass-3.6.4/src/extension.cpp",
    "3rp/libsass-3.6.4/contrib/plugin.cpp",

    "3rp/hacl-c/kremlib.c",
    "3rp/hacl-c/Hacl_SHA2_256.c",
    "3rp/hacl-c/FStar.c",
]
pkgconfig = []
cflags = []
lflags = ["-ldl"]

[variants]
default = []

[dependencies]
string = "1"
err = "1"
mem = "1"

[repos]
